[package]
name = "vertex_definition_compile_error_showcase"
version = "0.1.0"
authors = ["Felix Paul Niemeyer <niemeyer.felix@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.18.0"
vulkano-shaders = "0.18.0"
vulkano-win = "0.18.0"
winit = "0.22.2"
